import type { AiCoachScenario } from "@/lib/types/ai-coach";

export const AI_COACH_SCENARIOS: AiCoachScenario[] = [
  {
    id: "vip-anderson-b1",
    characterId: "anderson",
    title: "商务常客",
    subtitle: "VIP Quiet Room Request",
    department: "reception",
    level: "B1",
    guestName: "Mr. Anderson",
    guestPersona: "商务常客，需要安静房间以便清晨 7 点开电话会议",
    setting: "Front desk, 10:00 PM — frequent business guest checking in",
    description: "常客抵达，要求安静楼层、高速 Wi-Fi 并确认明早叫醒服务。",
    objectives: ["认出常客", "安排安静房间", "确认叫醒与网络"],
    keyPhrases: [
      { english: "Welcome back, Mr. Anderson.", chinese: "欢迎再次光临，Anderson 先生。" },
      { english: "I've placed you on a quiet floor.", chinese: "已为您安排安静楼层。" },
      { english: "A wake-up call at 6:30 AM is confirmed.", chinese: "已确认明早 6:30 叫醒。" },
    ],
    openingLine:
      "Good evening. I'm Mr. Anderson — I stay here often. I need a very quiet room; I have a conference call at 7 AM tomorrow.",
    openingLineCn: "晚上好，我是 Anderson 先生，经常住这里。我需要一个非常安静的房间，明天早上 7 点有电话会议。",
    imageCategory: "vip",
    turns: [
      {
        staffHint: "欢迎常客，确认安静楼层与房型",
        modelAnswer:
          "Welcome back, Mr. Anderson. We have a deluxe room on the 22nd executive floor — our quietest level. High-speed Wi-Fi is complimentary.",
        expectedKeywords: ["welcome", "quiet", "floor", "Wi-Fi", "deluxe"],
        guestGood: "That sounds perfect. Is breakfast available before 7 AM?",
        guestGoodCn: "听起来很好，7 点前能用早餐吗？",
        guestNeutral: "22nd floor is fine. What about the minibar prices?",
        guestNeutralCn: "22 楼可以，迷你吧价格呢？",
        guestPoor: "I hope it's actually quiet this time. Last stay was noisy.",
        guestPoorCn: "希望这次真的安静，上次很吵。",
      },
      {
        staffHint: "说明早餐时间，安排 6:30 叫醒",
        modelAnswer:
          "Breakfast opens at 6:30 AM in the restaurant. I've scheduled a wake-up call for 6:30 as well. May I see your ID to complete check-in?",
        expectedKeywords: ["breakfast", "6:30", "wake-up", "restaurant", "ID"],
        guestGood: "Excellent. Here's my passport.",
        guestGoodCn: "很好，这是我的护照。",
        guestNeutral: "6:30 works. I'll need a late check-out if possible.",
        guestNeutralCn: "6:30 可以，如可能我想延迟退房。",
        guestPoor: "6:30 is cutting it close. Can't breakfast open earlier?",
        guestPoorCn: "6:30 太赶了，早餐不能更早吗？",
      },
      {
        staffHint: "完成登记，递房卡并祝入住愉快",
        modelAnswer:
          "You're in room 2205. Here's your key card. If you need anything during your stay, please dial 0. Enjoy your evening, Mr. Anderson.",
        expectedKeywords: ["room", "key card", "dial", "enjoy", "evening"],
        guestGood: "Thank you. You've been very efficient.",
        guestGoodCn: "谢谢，效率很高。",
        guestNeutral: "Alright. Where is the gym?",
        guestNeutralCn: "好的，健身房在哪？",
        guestPoor: "I hope the room is actually ready. I don't want to wait.",
        guestPoorCn: "希望房间准备好了，我不想等。",
      },
    ],
  },
  {
    id: "tourist-elena-a2",
    characterId: "elena",
    title: "国际游客",
    subtitle: "Directions & City Map",
    department: "concierge",
    level: "A2",
    guestName: "Elena",
    guestPersona: "首次来华的俄罗斯游客，对交通和周边不熟悉",
    setting: "Concierge desk, 11:00 AM",
    description: "游客询问地铁、景点路线，并索取城市地图。",
    objectives: ["热情问候", "指路说明", "提供地图"],
    keyPhrases: [
      { english: "The nearest metro is five minutes on foot.", chinese: "最近地铁步行五分钟。" },
      { english: "Let me mark it on the map for you.", chinese: "让我在地图上标给您。" },
      { english: "Have a wonderful day exploring the city.", chinese: "祝您游玩愉快。" },
    ],
    openingLine:
      "Excuse me, I'm from Russia and this is my first time here. How do I get to the nearest metro station?",
    openingLineCn: "打扰一下，我来自俄罗斯，第一次来。怎么去最近的地铁站？",
    imageCategory: "concierge",
    turns: [
      {
        staffHint: "热情回应，说明地铁步行路线",
        modelAnswer:
          "Welcome, Elena! The nearest metro station is just a five-minute walk. Exit the hotel, turn left, and walk straight to the main road.",
        expectedKeywords: ["welcome", "metro", "five minutes", "walk", "left"],
        guestGood: "Thank you! Is there a city map I could have?",
        guestGoodCn: "谢谢！有城市地图吗？",
        guestNeutral: "Five minutes — is it easy to find?",
        guestNeutralCn: "五分钟——好找吗？",
        guestPoor: "Your directions are confusing. Can you be more specific?",
        guestPoorCn: "你说的太模糊了，能具体点吗？",
      },
      {
        staffHint: "提供地图，标注地铁和推荐景点",
        modelAnswer:
          "Of course! Here is a city map. I've marked the metro station and a popular shopping area nearby. Tickets can be bought at the station.",
        expectedKeywords: ["map", "marked", "metro", "tickets", "shopping"],
        guestGood: "This is very helpful. What time does the metro close?",
        guestGoodCn: "很有帮助，地铁几点关门？",
        guestNeutral: "Okay. How much is a metro ticket?",
        guestNeutralCn: "好的，地铁票多少钱？",
        guestPoor: "I don't read Chinese. Is the map in English?",
        guestPoorCn: "我不认识中文，地图有英文吗？",
      },
      {
        staffHint: "说明运营时间，推荐下载翻译 App",
        modelAnswer:
          "The metro runs until 11 PM. I also recommend downloading a translation app — many signs have English. Enjoy exploring!",
        expectedKeywords: ["11 PM", "translation", "English", "enjoy", "exploring"],
        guestGood: "Wonderful, thank you so much for your help!",
        guestGoodCn: "太好了，非常感谢！",
        guestNeutral: "Alright, I'll figure it out.",
        guestNeutralCn: "好的，我自己试试。",
        guestPoor: "I hope I don't get lost.",
        guestPoorCn: "希望我不会迷路。",
      },
    ],
  },
  {
    id: "complaint-higgins-b1",
    characterId: "higgins",
    title: "客房投诉",
    subtitle: "Housekeeping Issue",
    department: "reception",
    level: "B1",
    guestName: "Mrs. Higgins",
    guestPersona: "带家人入住，发现浴室清洁不到位，情绪不满",
    setting: "Front desk, 4:00 PM — guest returning from outing",
    description: "客人投诉浴室毛发和水渍，要求换房或彻底打扫。",
    objectives: ["真诚道歉", "了解问题", "提供换房或重清洁"],
    keyPhrases: [
      { english: "I'm very sorry to hear that.", chinese: "非常抱歉听到这个情况。" },
      { english: "We can arrange a room change immediately.", chinese: "我们可以立刻安排换房。" },
      { english: "Housekeeping will re-clean within thirty minutes.", chinese: "客房部三十分钟内重新打扫。" },
    ],
    openingLine:
      "I'm very disappointed. We just returned and the bathroom hasn't been cleaned properly — there are hairs and water stains everywhere!",
    openingLineCn: "我很失望。我们刚回来，浴室没打扫干净——到处是水渍和毛发！",
    imageCategory: "complaint",
    turns: [
      {
        staffHint: "道歉并表示重视，询问是否换房",
        modelAnswer:
          "I'm truly sorry, Mrs. Higgins. That's completely unacceptable. Would you prefer a room change, or shall we send housekeeping to re-clean immediately?",
        expectedKeywords: ["sorry", "unacceptable", "room change", "housekeeping", "immediately"],
        guestGood: "A room change would be better. We're on the 8th floor, room 803.",
        guestGoodCn: "换房更好，我们在 8 楼 803。",
        guestNeutral: "Can someone come now? My children need to shower.",
        guestNeutralCn: "能现在来人吗？孩子需要洗澡。",
        guestPoor: "This is disgusting! I expected better from a hotel like this.",
        guestPoorCn: "太恶心了！这种酒店不该这样。",
      },
      {
        staffHint: "安排同楼层安静房间，协助搬行李",
        modelAnswer:
          "I've arranged room 810 on the same floor — it's freshly prepared. May I send a bellman to help move your luggage?",
        expectedKeywords: ["arranged", "freshly", "bellman", "luggage", "floor"],
        guestGood: "Yes, please. How long will the move take?",
        guestGoodCn: "好的，搬房要多久？",
        guestNeutral: "810 is fine. Will we be charged extra?",
        guestNeutralCn: "810 可以，要加钱吗？",
        guestPoor: "This whole trip has been a nightmare because of this.",
        guestPoorCn: "因为这事整趟旅行都很糟。",
      },
      {
        staffHint: "说明免费换房，赠送水果拼盘致歉",
        modelAnswer:
          "There is no extra charge. A bellman will arrive in five minutes. We'd also like to send a complimentary fruit platter to apologize.",
        expectedKeywords: ["no charge", "five minutes", "complimentary", "fruit", "apologize"],
        guestGood: "Thank you. I appreciate you handling this quickly.",
        guestGoodCn: "谢谢，感谢你们快速处理。",
        guestNeutral: "Fine. I expect the new room to be spotless.",
        guestNeutralCn: "行吧，新房间必须一尘不染。",
        guestPoor: "A fruit platter doesn't make up for this.",
        guestPoorCn: "送水果弥补不了。",
      },
    ],
  },
  {
    id: "late-david-a2",
    characterId: "david",
    title: "深夜入住",
    subtitle: "Late Night Walk-in",
    department: "reception",
    level: "A2",
    guestName: "David",
    guestPersona: "航班延误 4 小时，凌晨 2 点疲惫抵达",
    setting: "Front desk, 2:15 AM",
    description: "疲惫散客深夜入住，询问是否还有房、餐厅是否营业。",
    objectives: ["表达同理", "查询房态", "说明夜间餐饮"],
    keyPhrases: [
      { english: "I'm sorry to hear about your delay.", chinese: "抱歉得知您的航班延误。" },
      { english: "We do have a room available.", chinese: "我们还有空房。" },
      { english: "Room service is available 24 hours.", chinese: "客房送餐 24 小时供应。" },
    ],
    openingLine:
      "Hi… sorry it's so late. My flight was delayed four hours. Do you still have any rooms? And is there anything to eat?",
    openingLineCn: "嗨……抱歉这么晚。航班延误了 4 小时，还有房吗？还有吃的吗？",
    imageCategory: "check-in",
    turns: [
      {
        staffHint: "表示理解，确认有空房并报价",
        modelAnswer:
          "I'm sorry about your delay, David. We have a king room available at 580 yuan, breakfast included. You must be exhausted.",
        expectedKeywords: ["sorry", "delay", "king room", "580", "breakfast"],
        guestGood: "Yes, I'm exhausted. I'll take it. Is room service open?",
        guestGoodCn: "是的，累坏了。我订了，客房送餐还开吗？",
        guestNeutral: "580 is fine. How late is room service?",
        guestNeutralCn: "580 可以，送餐到几点？",
        guestPoor: "I just want to sleep. Can we do this quickly?",
        guestPoorCn: "我只想睡觉，能快点吗？",
      },
      {
        staffHint: "说明 24 小时送餐，快速办理入住",
        modelAnswer:
          "Room service is available 24 hours — here's the menu. May I see your ID? I'll have you in your room within five minutes.",
        expectedKeywords: ["24 hours", "menu", "ID", "five minutes", "room"],
        guestGood: "Here's my passport. Something light — a sandwich would be great.",
        guestGoodCn: "护照给你，来点清淡的，三明治就好。",
        guestNeutral: "Here's my ID. Just the room for now.",
        guestNeutralCn: "证件给你，先要房间。",
        guestPoor: "Can someone else handle the paperwork? I can barely stand.",
        guestPoorCn: "能快点办吗？我快站不住了。",
      },
      {
        staffHint: "递房卡，安排送餐，祝晚安",
        modelAnswer:
          "You're in room 1502. Here's your key. I'll order a sandwich to your room. Have a good rest, David.",
        expectedKeywords: ["room", "key", "sandwich", "rest", "good"],
        guestGood: "Thank you. You've been a lifesaver.",
        guestGoodCn: "谢谢，真是帮了大忙。",
        guestNeutral: "Good night.",
        guestNeutralCn: "晚安。",
        guestPoor: "I hope the room is actually quiet.",
        guestPoorCn: "希望房间真的安静。",
      },
    ],
  },
  {
    id: "event-sarah-b1",
    characterId: "sarah",
    title: "宴会协调",
    subtitle: "Wedding Event Check",
    department: "concierge",
    level: "B1",
    guestName: "Sarah",
    guestPersona: "婚礼活动统筹人，需确认宴会厅布置与餐饮",
    setting: "Concierge desk, 2:00 PM — day before wedding",
    description: "活动统筹人确认宴会厅、桌数、音响及彩排时间。",
    objectives: ["确认身份", "核实布置细节", "安排彩排"],
    keyPhrases: [
      { english: "Let me confirm the ballroom details.", chinese: "让我确认宴会厅细节。" },
      { english: "Setup begins at 4 PM tomorrow.", chinese: "明日下午 4 点开始布置。" },
      { english: "The AV technician will be on-site at 2 PM.", chinese: "音响师下午 2 点到场。" },
    ],
    openingLine:
      "Hello, I'm Sarah — the wedding coordinator. I need to confirm the ballroom setup, table count, and catering for tomorrow.",
    openingLineCn: "你好，我是 Sarah，婚礼统筹。需确认明天的宴会厅布置、桌数和餐饮。",
    imageCategory: "concierge",
    turns: [
      {
        staffHint: "确认活动名称与桌数",
        modelAnswer:
          "Good afternoon, Sarah. I have the Wang-Zhang wedding on file — ballroom B, 20 tables for 200 guests. Is that correct?",
        expectedKeywords: ["wedding", "ballroom", "tables", "200", "correct"],
        guestGood: "Yes, 20 tables. Can we do a walk-through at 3 PM today?",
        guestGoodCn: "对，20 桌。今天 3 点能实地看一下吗？",
        guestNeutral: "20 tables, but we may add two more. Is that possible?",
        guestNeutralCn: "20 桌，但可能加 2 桌，可以吗？",
        guestPoor: "I called three times about this. I hope everything is ready.",
        guestPoorCn: "这事我打了三次电话，希望都准备好了。",
      },
      {
        staffHint: "安排 3 点实地查看，说明布置时间",
        modelAnswer:
          "A walk-through at 3 PM today is confirmed. Setup begins at 4 PM tomorrow. Our events team will contact you this evening.",
        expectedKeywords: ["walk-through", "3 PM", "setup", "4 PM", "events team"],
        guestGood: "Perfect. What about the sound system and microphone?",
        guestGoodCn: "很好，音响和麦克风呢？",
        guestNeutral: "3 PM works. Who is my main contact tomorrow?",
        guestNeutralCn: "3 点可以，明天主要联系人是谁？",
        guestPoor: "Last time the AV wasn't tested. I need guarantees.",
        guestPoorCn: "上次 AV 没测试，我需要保证。",
      },
      {
        staffHint: "说明音响师 2 点到场，提供联系人名片",
        modelAnswer:
          "The AV technician arrives at 2 PM for a full sound check. Here is my colleague's card — she'll be your on-site contact tomorrow.",
        expectedKeywords: ["AV", "2 PM", "sound check", "card", "contact"],
        guestGood: "Wonderful. Thank you for being so organized.",
        guestGoodCn: "太好了，感谢安排得这么周到。",
        guestNeutral: "Alright. I'll see you at 3.",
        guestNeutralCn: "好的，3 点见。",
        guestPoor: "I'll hold you responsible if anything goes wrong.",
        guestPoorCn: "出问题我会找你们负责。",
      },
    ],
  },
];

export function getAiCoachScenario(id: string): AiCoachScenario | undefined {
  return AI_COACH_SCENARIOS.find((s) => s.id === id);
}
